spring.application.name=Config-Server

server.port=8085



spring.cloud.config.server.git.uri=https://github.com/ashish-ashish05/Hotel-Rating-App-Config
spring.cloud.config.server.git.clone-on-start=true